### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'content'

### ISSUE THREAD

**Issue by LogarithmicJones** [slavingia/askmybook#7]
[OKAY] Loaded ENV .env File as KEY=VALUE Format
2:24:44 PM web.1 |  [2023-01-16 14:24:44 -0700] [226789] [INFO] Starting gunicorn 20.1.0
2:24:44 PM web.1 |  [2023-01-16 14:24:44 -0700] [226789] [INFO] Listening at: http://0.0.0.0:33555 (226789)
2:24:44 PM web.1 |  [2023-01-16 14:24:44 -0700] [226789] [INFO] Using worker: sync
2:24:44 PM web.1 |  [2023-01-16 14:24:44 -0700] [226790] [INFO] Booting worker with pid: 226790
2:24:48 PM web.1 |  Internal Server Error: /ask
2:24:48 PM web.1 |  Traceback (most recent call last):
2:24:48 PM web.1 |    File "/home/loganjones/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
2:24:48 PM web.1 |      response = get_response(request)
2:24:48 PM web.1 |                 ^^^^^^^^^^^^^^^^^^^^^
2:24:48 PM web.1 |    File "/home/loganjones/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
2:24:48 PM web.1 |      response = wrapped_callback(request, *callback_args, **callback_kwargs)
2:24:48 PM web.1 |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2:24:48 PM web.1 |    File "/home/loganjones/.local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
2:24:48 PM web.1 |      return view_func(*args, **kwargs)
2:24:48 PM web.1 |             ^^^^^^^^^^^^^^^^^^^^^^^^^^
2:24:48 PM web.1 |    File "/home/loganjones/CMPUT/QueryMyBook/hello/views.py", line 167, in ask
2:24:48 PM web.1 |      document_embeddings = load_embeddings('book.pdf.embeddings.csv')
2:24:48 PM web.1 |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2:24:48 PM web.1 |    File "/home/loganjones/CMPUT/QueryMyBook/hello/views.py", line 84, in load_embeddings
2:24:48 PM web.1 |      max_dim = max([int(c) for c in df.columns if c != "title"])
2:24:48 PM web.1 |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2:24:48 PM web.1 |    File "/home/loganjones/CMPUT/QueryMyBook/hello/views.py", line 84, in <listcomp>
2:24:48 PM web.1 |      max_dim = max([int(c) for c in df.columns if c != "title"])
2:24:48 PM web.1 |                     ^^^^^^
2:24:48 PM web.1 |  ValueError: invalid literal for int() with base 10: 'content'

**Comment by LogarithmicJones** [comment]
pdf_to_embeddings script is only creating the pages.csv, and not the embeddings.csv. When I run the script it goes through the entire book makes the pages.csv  and then pauses until I keyboard interrupt.

^CTraceback (most recent call last):
  File "/home/loganjones/CMPUT/QueryMyBook/scripts/pdf_to_pages_embeddings.py", line 99, in <module>
    doc_embeddings = compute_doc_embeddings(df)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/loganjones/CMPUT/QueryMyBook/scripts/pdf_to_pages_embeddings.py", line 92, in compute_doc_embeddings
    return {
           ^
  File "/home/loganjones/CMPUT/QueryMyBook/scripts/pdf_to_pages_embeddings.py", line 93, in <dictcomp>
    idx: get_doc_embedding(r.content) for idx, r in df.iterrows()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/loganjones/CMPUT/QueryMyBook/scripts/pdf_to_pages_embeddings.py", line 84, in get_doc_embedding
    return get_embedding(text, DOC_EMBEDDINGS_MODEL)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/loganjones/CMPUT/QueryMyBook/scripts/pdf_to_pages_embeddings.py", line 77, in get_embedding
    result = openai.Embedding.create(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/loganjones/.local/lib/python3.11/site-packages/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/loganjones/.local/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/home/loganjones/.local/lib/python3.11/site-packages/openai/api_requestor.py", line 217, in request
    result = self.request_raw(
             ^^^^^^^^^^^^^^^^^
  File "/home/loganjones/.local/lib/python3.11/site-packages/openai/api_requestor.py", line 517, in request_raw
    result = _thread_context.session.request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib64/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
